/*
 *
 *  constants
 *
 */

export default function constants(name) {
  const url = `lg/${name}`;

  return {
    LOAD_RECORD: `${url}/LOAD_RECORD`,
    LOAD_RECORD_SUCCESS: `${url}/LOAD_RECORD_SUCCESS`,
    LOAD_RECORD_ERROR: `${url}/LOAD_RECORD_ERROR`,
    LOAD_RECORDS: `${url}/LOAD_RECORDS`,
    LOAD_RECORDS_SUCCESS: `${url}/LOAD_RECORDS_SUCCESS`,
    LOAD_RECORDS_ERROR: `${url}/LOAD_RECORDS_ERROR`,
    CREATE_RECORD: `${url}/CREATE_RECORD`,
    CREATE_RECORD_SUCCESS: `${url}/CREATE_RECORD_SUCCESS`,
    CREATE_RECORD_ERROR: `${url}/CREATE_RECORD_ERROR`,
    UPDATE_RECORD: `${url}/UPDATE_RECORD`,
    UPDATE_RECORD_SUCCESS: `${url}/UPDATE_RECORD_SUCCESS`,
    UPDATE_RECORD_ERROR: `${url}/UPDATE_RECORD_ERROR`,
    DELETE_RECORD: `${url}/DELETE_RECORD`,
    DELETE_RECORD_SUCCESS: `${url}/DELETE_RECORD_SUCCESS`,
    DELETE_RECORD_ERROR: `${url}/DELETE_RECORD_ERROR`,
    LOAD_RECORDS_VALID_CACHE: `${url}/LOAD_RECORDS_VALID_CACHE`,
  };
}
